# Generated by Django 2.2.6 on 2019-10-15 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='datetime',
            new_name='datetime_event',
        ),
        migrations.AddField(
            model_name='event',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
