# Generated by Django 2.2.6 on 2019-10-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20191015_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime_event',
            field=models.DateTimeField(verbose_name='Event Date - Please Format YYYY-MM-DD HH:MM'),
        ),
    ]
