# Generated by Django 2.2.6 on 2019-10-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20191023_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='imagePlaceholder.jpg', upload_to='event_pics'),
        ),
    ]
