# Generated by Django 2.2.6 on 2019-11-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20191113_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='RGU.jpg', upload_to='event_pics'),
        ),
    ]
