# Generated by Django 2.2.6 on 2019-11-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20191113_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='RGU.jpg', upload_to='profile_pics'),
        ),
    ]
