# Generated by Django 2.2.6 on 2019-11-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20191116_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime_event',
            field=models.DateField(verbose_name='Event Date - Please Format YYYY-MM-DD HH:MM'),
        ),
    ]
