# Generated by Django 2.2.6 on 2019-11-16 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20191116_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='datetime_event',
        ),
        migrations.AddField(
            model_name='event',
            name='date_event',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_event',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Time'),
        ),
    ]
