# Generated by Django 2.2.6 on 2019-11-16 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20191116_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_event',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Time'),
        ),
    ]
