# Generated by Django 2.2.6 on 2019-11-16 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20191116_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_event',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Time'),
        ),
    ]
