# Generated by Django 2.2.6 on 2019-11-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_end_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_event',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='time_event',
            new_name='start_time',
        ),
    ]
