# Generated by Django 2.2.6 on 2019-11-16 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20191116_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_event',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
