# Generated by Django 2.2.6 on 2019-10-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191025_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='event',
            new_name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='year_in_school',
            field=models.CharField(choices=[('U1', 'Undergraduate - Year 1'), ('U3', 'Undergraduate - Year 2'), ('U3', 'Undergraduate - Year 3'), ('U4', 'Undergraduate - Year 4'), ('PG', 'Postgraduate'), ('VN', 'Volunteer')], default='U1', max_length=2),
        ),
    ]
