# Generated by Django 2.2.6 on 2019-10-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191025_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='year_in_school',
        ),
    ]
